[package]
name = "mwmr"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true

[features]
default = ["std"]
std = ["indexmap/default", "wmark/default"]

# Features will export the generic unit tests implementation for database based on mwmr
test = ["rand"]

[dependencies]
bytes.workspace = true
bitflags.workspace = true
cheap-clone.workspace = true
crossbeam-channel.workspace = true
crossbeam-utils.workspace = true
either.workspace = true
indexmap.workspace = true
parking_lot.workspace = true
scopeguard = "1"
smallvec-wrapper.workspace = true
once_cell = "1"
thiserror.workspace = true
tracing.workspace = true
wmark.workspace = true

rand = { version = "0.8", optional = true }

[dev-dependencies]
rand = "0.8"

[[test]]
name = "mwmr"
path = "tests/main.rs"
required-features = ["test"]